name: تشغيل البوت 24/7

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: تحميل الكود
        uses: actions/checkout@v4

      - name: تثبيت Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: تثبيت ffmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --fix-missing ffmpeg

      - name: تثبيت المكتبات
        run: pip install -r requirements.txt

      - name: تشغيل البوت
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          FB_PAGE_ACCESS_TOKEN: ${{ secrets.FB_PAGE_ACCESS_TOKEN }}
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: python main.py
